# Mostly boilerplate image spec, taken from nextjs docs:
# https://nextjs.org/docs/pages/building-your-application/deploying#docker-image

FROM docker.io/node:18-slim AS builder
LABEL maintainer="team@penumbralabs.xyz"
# Enable `pnpm` so we can use it instead of `npm` in builds.
RUN corepack enable pnpm
# Disable nextjs telemetry in base layer, so the env var carries over to other layers.
ENV NEXT_TELEMETRY_DISABLED 1

# Create normal user for app
RUN addgroup --system --gid 1001 nodejs
# Set the correct permission for prerender cache
RUN adduser --system --uid 1001 nextjs

# Install node dependencies only when needed
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# Rebuild the source code only when needed
COPY . .
# Build the website as standalone output.
RUN pnpm --version && node --version && pnpm run build


# Copy standalone directories for serving.
RUN mv /app/.next/standalone /app/docroot \
  && mv /app/.next/static /app/docroot/.next/ \
  && mv /app/public /app/docroot/

RUN chown -R nextjs:nodejs /app
WORKDIR /app/docroot
# RUN apt-get update && apt-get install tree && tree -a -L 3 

USER nextjs
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD node server.js
