# Mostly boilerplate image spec, taken from nextjs docs:
# https://nextjs.org/docs/pages/building-your-application/deploying#docker-image

FROM docker.io/node:20-alpine AS base
# Enable `pnpm` so we can use it instead of `npm` in builds.
RUN corepack enable pnpm
# Disable nextjs telemetry in base layer, so the env var carries over to other layers.
ENV NEXT_TELEMETRY_DISABLED 1
LABEL maintainer="team@penumbralabs.xyz"

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Create normal user for app
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# build is all
COPY .next/standalone /app
RUN chown -R nextjs:nodejs /app

USER nextjs
EXPOSE 3000
ENV HOSTNAME="0.0.0.0"

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["node", "server.js"]
